# Generated by Django 6.0.6 on 2026-06-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('talla', models.CharField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='calzados/')),
                ('color', models.CharField(default='Negro', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calzados', to='tienda.marca')),
            ],
            options={
                'verbose_name': 'Calzado',
                'verbose_name_plural': 'Calzados',
                'ordering': ['modelo'],
            },
        ),
    ]
